# /// script
# requires-python = ">=3.12"
# ///
"""Generate ``src/kpip`` and ``tests`` from upstream pip and kpip's patches.

kpip is upstream pip with its package renamed to ``kpip`` and the patches in
``tools/vendoring/patches/pip`` applied on top, in name order. Both trees are
generated by this script and committed; never edit them by hand.

Usage::

    uv run scripts/vendor_pip.py sync                # latest pip ``main``
    uv run scripts/vendor_pip.py sync --commit SHA   # a specific pip commit
    uv run scripts/vendor_pip.py check               # committed trees are current
    uv run scripts/vendor_pip.py export              # write build/pip's commits as patches

``sync`` leaves a git checkout in ``build/pip`` with three branches:
``upstream`` (pip itself), ``base`` (``upstream`` plus the rename) and
``kpip`` (``base`` plus one commit per patch). To change the patches, commit
on ``kpip`` (``git rebase -i base`` to edit an existing one), then ``export``
and ``sync``. When upstream moves and a patch no longer applies, ``sync``
stops mid-``git am`` in ``build/pip``: resolve it there, ``git am
--continue``, then ``export`` and ``sync``.

The commit the committed trees came from is recorded in
``tools/vendoring/pip-upstream.txt``; ``check`` regenerates from it.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

PIP_REPOSITORY = "https://github.com/pypa/pip.git"
# Always its latest commit unless ``--commit`` names another.
PIP_BRANCH = "main"

REPO_ROOT = Path(__file__).resolve().parents[1]
PATCHES_DIR = REPO_ROOT / "tools" / "vendoring" / "patches" / "pip"
UPSTREAM_FILE = REPO_ROOT / "tools" / "vendoring" / "pip-upstream.txt"
WORK_DIR = REPO_ROOT / "build" / "pip"

# Trees copied out of the checkout, relative to both it and the repository.
TREES = (Path("src") / "kpip", Path("tests"))

UPSTREAM_BRANCH = "upstream"
BASE_BRANCH = "base"
PATCHED_BRANCH = "kpip"

# Module references only; user-facing "pip" text is left to the patches.
RENAMES = (
    (re.compile(r"\bpip(?=\.(?:_internal|_vendor|__\w+__)\b)"), "kpip"),
    (re.compile(r"^(\s*)from pip import\b", re.MULTILINE), r"\1from kpip import"),
    (re.compile(r"^(\s*)import pip\b", re.MULTILINE), r"\1import kpip"),
)
RENAMED_SUFFIXES = {".py", ".pyi"}
# Files that also name the package as a string, where every "pip" literal is
# the module name.
RENAMED_MODULE_STRINGS = (Path("src") / "kpip" / "__pip-runner__.py",)

VERSION_FILE = Path("src") / "kpip" / "__init__.py"
_VERSION_ASSIGNMENT = re.compile(r'^__version__ = "(?P<version>[^"]+)"$', re.MULTILINE)

# Commits the script makes itself; patches keep their own authors.
GIT_IDENTITY = ("-c", "user.name=kpip vendor_pip", "-c", "user.email=kpip@invalid")


class PatchError(RuntimeError):
    pass


def _git(*args: str, cwd: Path, capture: bool = False) -> str:
    result = subprocess.run(
        ["git", *GIT_IDENTITY, *args],
        cwd=cwd,
        check=True,
        text=True,
        stdout=subprocess.PIPE if capture else None,
    )
    return result.stdout or ""


def _remove_tree(path: Path) -> None:
    """``shutil.rmtree`` that also removes read-only files (git objects on Windows)."""

    def make_writable_and_retry(function, target, _error) -> None:
        os.chmod(target, stat.S_IWRITE)
        function(target)

    shutil.rmtree(path, onexc=make_writable_and_retry)


def resolve_commit(repository: str = PIP_REPOSITORY, branch: str = PIP_BRANCH) -> str:
    """The branch's current commit, without fetching anything."""
    output = subprocess.run(
        ["git", "ls-remote", "--exit-code", repository, f"refs/heads/{branch}"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return output.split()[0]


def find_patches(patches_dir: Path = PATCHES_DIR) -> list[Path]:
    """Patches apply in name order, hence the numeric prefixes."""
    return sorted(patches_dir.glob("*.patch")) if patches_dir.is_dir() else []


def rename_package(checkout: Path) -> None:
    """Move ``src/pip`` to ``src/kpip`` and point every module reference at it."""
    _git("mv", "src/pip", "src/kpip", cwd=checkout)
    for tree in TREES:
        for path in (checkout / tree).rglob("*"):
            if path.suffix not in RENAMED_SUFFIXES or not path.is_file():
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            renamed = text
            for pattern, replacement in RENAMES:
                renamed = pattern.sub(replacement, renamed)
            if path.relative_to(checkout) in RENAMED_MODULE_STRINGS:
                renamed = renamed.replace('"pip"', '"kpip"')
            if renamed != text:
                path.write_text(renamed, encoding="utf-8", newline="")


def kpip_version() -> str:
    with (REPO_ROOT / "pyproject.toml").open("rb") as pyproject:
        return tomllib.load(pyproject)["project"]["version"]


def stamp_version(checkout: Path) -> None:
    """Make ``__version__`` kpip's and keep pip's as ``__pip_version__``.

    ``scripts/bump_version.py`` rewrites the ``__version__`` literal the same
    way, so a bump needs no re-sync.
    """
    path = checkout / VERSION_FILE
    text = path.read_text(encoding="utf-8")
    stamped, count = _VERSION_ASSIGNMENT.subn(
        lambda match: (
            f'__version__ = "{kpip_version()}"\n'
            "# The pip release kpip is built from.\n"
            f'__pip_version__ = "{match["version"]}"'
        ),
        text,
    )
    if count != 1:
        raise RuntimeError(f"expected one __version__ assignment in {VERSION_FILE}")
    path.write_text(stamped, encoding="utf-8", newline="")


def generate(commit: str, checkout: Path) -> None:
    """Build the patched pip checkout at ``checkout`` from ``commit``."""
    if checkout.exists():
        _remove_tree(checkout)
    checkout.mkdir(parents=True)

    _git("init", "--quiet", cwd=checkout)
    _git("fetch", "--quiet", "--depth", "1", PIP_REPOSITORY, commit, cwd=checkout)
    _git("checkout", "--quiet", "-b", UPSTREAM_BRANCH, "FETCH_HEAD", cwd=checkout)

    _git("checkout", "--quiet", "-b", PATCHED_BRANCH, cwd=checkout)
    rename_package(checkout)
    stamp_version(checkout)
    _git("add", "--all", cwd=checkout)
    _git("commit", "--quiet", "-m", "Rename pip to kpip", cwd=checkout)
    _git("branch", BASE_BRANCH, cwd=checkout)

    for patch in find_patches():
        print(f"Applying {patch.name}", flush=True)
        try:
            _git("am", "--quiet", "--keep-cr", str(patch), cwd=checkout)
        except subprocess.CalledProcessError as error:
            raise PatchError(
                f"{patch.name} no longer applies to pip {commit[:12]}; resolve it "
                f"in {checkout}, run `git am --continue`, then `export` and `sync`"
            ) from error


def _ignored_files(destination: Path) -> list[Path]:
    """Files git ignores under ``TREES`` in ``destination``, but for bytecode:
    what was put there, such as the functional tests' common wheels."""
    if not (destination / ".git").exists():
        return []
    output = subprocess.run(
        ["git", "ls-files", "-z", "--others", "--ignored", "--exclude-standard", "--"]
        + [str(tree) for tree in TREES],
        cwd=destination,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return [
        Path(name)
        for name in output.split("\0")
        if name and "__pycache__" not in Path(name).parts and not name.endswith(".pyc")
    ]


def copy_out(checkout: Path, destination: Path) -> None:
    """Replace each of ``TREES`` under ``destination`` with the checkout's,
    keeping what git ignores there."""
    with tempfile.TemporaryDirectory() as kept:
        ignored = _ignored_files(destination)
        for path in ignored:
            (Path(kept) / path).parent.mkdir(parents=True, exist_ok=True)
            shutil.move(destination / path, Path(kept) / path)
        for tree in TREES:
            target = destination / tree
            if target.exists():
                _remove_tree(target)
            shutil.copytree(
                checkout / tree,
                target,
                ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
            )
        for path in ignored:
            (destination / path).parent.mkdir(parents=True, exist_ok=True)
            shutil.move(Path(kept) / path, destination / path)


def sync(commit: str | None) -> None:
    commit = commit or resolve_commit()
    print(f"pip {commit}", flush=True)
    generate(commit, WORK_DIR)
    copy_out(WORK_DIR, REPO_ROOT)
    UPSTREAM_FILE.write_text(commit + "\n", encoding="utf-8")


def _repository_files() -> set[Path]:
    """Files under ``TREES`` that git would commit: tracked or not ignored, and present."""
    output = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard", "--"]
        + [str(tree) for tree in TREES],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return {
        Path(name)
        for name in output.split("\0")
        if name and (REPO_ROOT / name).is_file()
    }


def _generated_files(root: Path) -> set[Path]:
    return {
        path.relative_to(root)
        for tree in TREES
        for path in (root / tree).rglob("*")
        if path.is_file()
    }


def check() -> int:
    commit = UPSTREAM_FILE.read_text(encoding="utf-8").strip()
    with tempfile.TemporaryDirectory() as scratch:
        scratch_root = Path(scratch)
        generate(commit, scratch_root / "pip")
        copy_out(scratch_root / "pip", scratch_root / "out")
        generated = _generated_files(scratch_root / "out")
        committed = _repository_files()
        stale = sorted(
            [f"missing  {path}" for path in generated - committed]
            + [f"extra    {path}" for path in committed - generated]
            + [
                f"modified {path}"
                for path in generated & committed
                if (scratch_root / "out" / path).read_bytes()
                != (REPO_ROOT / path).read_bytes()
            ],
            key=lambda line: line[9:],
        )
    for line in stale:
        print(line)
    current = not stale
    if not current:
        print(
            "The committed trees differ from pip "
            f"{commit[:12]} plus the patches; run `sync --commit {commit}`",
            file=sys.stderr,
        )
    return 0 if current else 1


def export() -> None:
    """Write the checkout's ``base..kpip`` commits over the patch series."""
    PATCHES_DIR.mkdir(parents=True, exist_ok=True)
    for patch in find_patches():
        patch.unlink()
    _git(
        "format-patch",
        "--quiet",
        "--zero-commit",
        "--no-signature",
        "--no-numbered",
        "-o",
        str(PATCHES_DIR),
        f"{BASE_BRANCH}..{PATCHED_BRANCH}",
        cwd=WORK_DIR,
    )
    for patch in find_patches():
        print(patch.relative_to(REPO_ROOT))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    sync_parser = commands.add_parser("sync", help="regenerate src/kpip and tests")
    sync_parser.add_argument("--commit", help="pip commit (default: latest main)")
    commands.add_parser("check", help="fail if the committed trees are stale")
    commands.add_parser("export", help="write build/pip's commits as patches")
    args = parser.parse_args(argv)

    try:
        if args.command == "sync":
            sync(args.commit)
        elif args.command == "check":
            return check()
        else:
            export()
    except PatchError as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
